### ISSUE TITLE
Import fprint 

### ISSUE THREAD

**Issue by duygucinar** [jdiego/python-libfprint#2]
`Traceback (most recent call last):
 File "examples/list_devices.py", line 4, in <module>
    import fprint
ImportError: /home/duygu/.local/lib/python3.6/site-packages/fprint.cpython-36m-x86_64-linux-gnu.so: undefined symbol: fp_minutia_get_coords`

When I try run example codes, I get this error

**Comment by admiralmaggie** [comment]
@duygucinar I'm receiving the exact same error. Were you able to figure out how to resolve this?

**Comment by stephennacion06** [comment]
@duygucinar Hello how did you resolve this issue thanks!
